# Generated by Django 5.2.17 on 2026-08-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
