# Generated by Django 5.2.17 on 2026-08-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Marca si la compra ya fue retirada'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Marca si la venta ya fue entregada'),
        ),
    ]
