# Generated by Django 5.2.17 on 2026-08-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_purchase_is_completed_sale_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='fulfillment_date',
            field=models.DateField(blank=True, help_text='Fecha en que debo retirar o recibir por envío', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_shipping',
            field=models.BooleanField(default=False, help_text='Marca si es por envío en vez de retiro presencial'),
        ),
        migrations.AddField(
            model_name='sale',
            name='fulfillment_date',
            field=models.DateField(blank=True, help_text='Fecha en que debo entregar o enviar', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_shipping',
            field=models.BooleanField(default=False, help_text='Marca si es por envío en vez de entrega presencial'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(help_text='Fecha en que se concretó la compra'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(help_text='Fecha en que se concretó la venta'),
        ),
    ]
