# Generated by Django 5.2.17 on 2026-08-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_purchase_owner_alter_sale_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='is_found',
            field=models.BooleanField(default=False, help_text='Marca si la carta ya fue encontrada/revisada'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_found',
            field=models.BooleanField(default=False, help_text='Marca si la carta ya fue encontrada/revisada'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
