# Generated by Django 5.2.17 on 2026-08-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(choices=[('NORMAL', 'Normal'), ('FOIL', 'Foil'), ('ALT_ART', 'Arte Alternativo'), ('SP', 'Special / Secret Rare'), ('PRE', 'Pre-release')], default='NORMAL', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
