# Generated by Django 5.2.17 on 2026-08-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['code', 'version']},
        ),
        migrations.AddField(
            model_name='card',
            name='image_suffix',
            field=models.CharField(blank=True, help_text='Ej: vacío=normal, _p1, _p2', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('code', 'version')},
        ),
    ]
