# Generated by Django 5.2.17 on 2026-08-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='maps_link',
            field=models.URLField(blank=True, help_text='URL de embed de Google Maps (iframe)'),
        ),
    ]
