# Generated by Django 5.2.17 on 2026-08-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_maps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='location',
            name='maps_link',
            field=models.URLField(blank=True, help_text='URL de embed de Google Maps (iframe)', max_length=500),
        ),
    ]
