# Generated by Django 5.2.17 on 2026-08-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_location_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='maps_link',
            field=models.URLField(blank=True, help_text='URL de Google Maps (link o embed)', max_length=1000),
        ),
    ]
